### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [zxytim/pdf2images#5]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.6. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pdf2images -w /tmp/ext pdf2images==0.0.6
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pdf2images==0.0.6
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/337/86e248a2fd879/pdf2images-0.0.6.tar.gz (6.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-o77t0id7/pdf2images/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-o77t0id7/pdf2images/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-o77t0id7/pdf2images/pip-egg-info
         cwd: /tmp/pip-wheel-o77t0id7/pdf2images/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-o77t0id7/pdf2images/setup.py", line 7, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jayvdb** [comment]
ping @zxytim .  Typically this is fixed by adding a `MANIFEST.in`
